travis:
  secure:
    BINSTAR_TOKEN: XAtvTSRw2RURH90SDryG7gPGqULrXq7vI3Ap5kfvR9qJjC9TtsHyvjE86jCGUVwRaf8mO5DveW/A308eP2T8D3PY2rgn+PG0rSp5TtAsMPiNoX+9prflxlqmhTj8m3NkgiWMWGwYgt0GfJ41WGd6RZJg8T2/zMVD8ACutbKeJvyHbznH0o6av/zkCUM/T8EOsWU2xpZDiBAJG6GIEk1srhbHh4WwP2J0xnYOdeWISYG+/EgQG6qJg43ktcw2E6+tJTCo57roMZGRD/Ozt2nV0ySq+EXLz41k5TcnVS0qY0yGgm/JuwOy7s8sfc5dLHWIfM0Gy4DDbTEQI/VtkXeyGQSWTF0/CVBCSnt8G6mPx6gr02FMAByVZ7VMua/m8OI5dQgIElWRgtNE9AQujjl8/Kc1DWXvKgGRw27ZZRFXtuN6/w0YyNuZJkXgO5EMlGIFNJcB409WL3a5Ee2JQiQZwA/pLWVKqYHXFkMhJA/MeHI4XZ6SUjmN/CnFaSMZSYFl3cfymHpVCXAJiWw3YsIz3M8sw6J+We0xVeRXZFD0LjGpCxtG4PcigGUW3kvizQ624bQ6Dkmf+sM358VbSotoag2B8WW+zRBLxtJ0gqfRH3djLY2GzlQMbUEIKW5K2vsOnm8J06wQSxNphmM3CevBaN0g4t/pLu/E6bjvWk5ieNM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
